### ISSUE TITLE
fs.readFileSync won't read files >512kb

### ISSUE THREAD

**Issue by halfninja** [nodyn/nodyn#107]
```
> s = fs.readFileSync('/var/tmp/d.json');
RangeError: Attempt to allocate Buffer larger than maximum size: 0x80000 bytes
  at <native function: RangeError> (org/dynjs/runtime/builtins/types/BuiltinRangeError.java:0:0)
  at Buffer (buffer.js:65:5)
  at readFileSync (fs.js:333:7)
  at <eval> (repl:1:0)
```

The file size is 616734. I hit this when trying to use the `caniuse-db` module, which has a JSON datafile of ~600k.

I had a go at reading it in with `readFile` as well, but got this error which seems even more suspect, as the file size is not that big:

```
[RangeError: File size is greater than possible Buffer: 0x3FFFFFFF bytes]
```

**Comment by halfninja** [comment]
I think the main reason is because fs.js does this to find out the largest buffer it can possibly allocate:

```
require('smalloc').kMaxLength
```

which returns `1073741823` on native Node, `524288` on Nodyn. The final error in the description above is just misleading - the message says 0x3FFFFFFF regardless of what the actual kMaxLength is.

**Comment by halfninja** [comment]
Okay, I can see that the 512k value is defined in https://github.com/nodyn/nodyn/blob/master/src/main/javascript/nodyn/bindings/smalloc.js - is there any chance it could be set to a much larger value, and leave it up to users to be sensible with their own memory?
